"""
Backtest the MESA Phase Band Trend strategy on MES, MNQ, MGC and MCL.

    python -m mesa_band.run                # all datasets, writes mesa_band/RESULTS.md
    python -m mesa_band.run --no-report    # console only

Datasets (sample_data/real_multi_instrument/):
  - Micro contracts, 15m, 2025-09-30 -> 2026-08-25 (MES, MNQ, MGC, MCL).
  - Micro contracts, 5m, 2026-05-10 -> 2026-08-25 (MES, MNQ, MGC, MCL).
  - Full-size ES / NQ / GC 15m, 2016 -> 2026, priced at the MICRO point
    value (MES / MNQ / MGC proxies -- same price series, 1/10 the $/point).
    There is no long CL history in the repo, so MCL only has the ~11-month run.
"""

import argparse
from pathlib import Path

import pandas as pd

import numpy as np

from .strategy import INSTRUMENTS, Params, prepare, run, summarize

EVAL_MAX_DAYS = 60  # trading days per evaluation attempt before it counts as TIMEOUT
EVAL_EVERY = 5  # start a new attempt every N trading days (weekly)

DATA = Path(__file__).resolve().parent.parent / "sample_data" / "real_multi_instrument"

DATASETS = [
    # (label, instrument, file)
    ("MES 15m 2025-26", "MES", "real_mes_15m_2025-09-30_2026-08-25.parquet"),
    ("MNQ 15m 2025-26", "MNQ", "real_mnq_15m_2025-09-30_2026-08-25.parquet"),
    ("MGC 15m 2025-26", "MGC", "real_mgc_15m_2025-09-30_2026-08-25.parquet"),
    ("MCL 15m 2025-26", "MCL", "real_mcl_15m_2025-09-30_2026-08-25.parquet"),
    ("MES 5m 2026", "MES", "real_mes_5m_2026-05-10_2026-08-25.parquet"),
    ("MNQ 5m 2026", "MNQ", "real_mnq_5m_2026-05-10_2026-08-25.parquet"),
    ("MGC 5m 2026", "MGC", "real_mgc_5m_2026-05-10_2026-08-25.parquet"),
    ("MCL 5m 2026", "MCL", "real_mcl_5m_2026-05-10_2026-08-25.parquet"),
    ("MES (ES data) 15m 2016-26", "MES", "real_es_15m_2016-05-29_2026-08-25.parquet"),
    ("MNQ (NQ data) 15m 2016-26", "MNQ", "real_nq_15m_2016-05-29_2026-08-25.parquet"),
    ("MGC (GC data) 15m 2016-26", "MGC", "real_gc_15m_2016-05-26_2026-08-25.parquet"),
]


def load(path: Path) -> pd.DataFrame:
    df = pd.read_parquet(path)
    df.columns = [c.lower() for c in df.columns]
    df.index = pd.DatetimeIndex(df.index).tz_convert("UTC")
    return df.sort_index()[["open", "high", "low", "close"]].dropna()


def fmt_money(x):
    return f"{x:,.0f}"


def run_all(p: Params):
    rows, evals, yearly = [], [], {}
    for label, sym, fname in DATASETS:
        df = load(DATA / fname)
        inst = INSTRUMENTS[sym]
        prep = prepare(df, p)
        cont = run(df, inst, p, mode="continuous", prep=prep)
        s = summarize(cont.trades, cont.daily_pnl)
        s["label"] = label
        s["period"] = f"{df.index[0]:%Y-%m-%d} -> {df.index[-1]:%Y-%m-%d}"
        rows.append(s)

        # Rolling evaluations: a fresh account every EVAL_EVERY trading days,
        # skipping the indicator warm-up and any start too close to the end
        # of the data to finish EVAL_MAX_DAYS.
        tday = prep["tday"]
        day_starts = np.flatnonzero(np.r_[True, tday[1:] != tday[:-1]])
        warm = max(p.trend_length, p.vol_length) + 50
        day_starts = day_starts[day_starts > warm]
        starts = day_starts[: max(len(day_starts) - EVAL_MAX_DAYS, 0): EVAL_EVERY]
        attempts = []
        for st in starts:
            attempts += run(df, inst, p, mode="evaluation", start=int(st),
                            max_days=EVAL_MAX_DAYS, prep=prep).attempts
        n = len(attempts)
        passed = [a for a in attempts if a.result == "PASSED"]
        failed = [a for a in attempts if a.result == "FAILED"]
        timeout = [a for a in attempts if a.result == "TIMEOUT"]
        pct = lambda k: 100.0 * k / n if n else float("nan")
        evals.append({
            "label": label,
            "attempts": n,
            "pass": pct(len(passed)),
            "fail": pct(len(failed)),
            "timeout": pct(len(timeout)),
            "consistent": pct(sum(a.best_day <= 0.5 * p.profit_target for a in passed)),
            "days_pass": float(np.median([a.days for a in passed])) if passed else float("nan"),
            "days_fail": float(np.median([a.days for a in failed])) if failed else float("nan"),
            "timeout_pnl": float(np.mean([a.pnl for a in timeout])) if timeout else float("nan"),
        })

        if "2016" in label:
            t = pd.DataFrame({"year": [x.exit_time.year for x in cont.trades],
                              "pnl": [x.pnl for x in cont.trades]})
            yearly[label] = t.groupby("year")["pnl"].agg(["count", "sum"])
        print(f"done: {label}")
    return rows, evals, yearly


def report(p: Params, rows, evals, yearly) -> str:
    out = ["# MESA Phase Band Trend -- backtest results", ""]
    out.append("Generated by `python -m mesa_band.run` (a Python port of "
               "`tradingview/mesa_phase_band_trend.pine`, default inputs).")
    out.append("")
    out.append(f"Settings: stop {p.atr_stop_mult}x ATR({p.atr_length}), target {p.target_r}R, "
               f"risk ${p.risk_per_trade:.0f}/trade, max {p.max_contracts} micros, "
               f"entries {p.entry_start:04d}-{p.entry_end:04d} ET, flat by {p.flatten_hhmm:04d} ET, "
               f"max {p.max_trades_day} trades/day, daily loss guard ${p.daily_loss_limit:.0f}. "
               "Costs: $0.62/side commission per micro + 1 tick slippage on market and stop fills.")
    out.append("")
    out.append("Caveats: the 2016-26 rows use full-size ES/NQ/GC prices with micro point values "
               "(unadjusted continuous contracts, so roll gaps can cause a false regime flip; positions "
               "are always flat overnight so gaps never hit P&L directly). There is no long MCL "
               "history in the repo. The 5m micro set is only ~3.5 months (4 evaluation starts), too "
               "short to conclude anything. Fills are simulated from OHLC bars, not ticks.")
    out.append("")
    out.append("## Continuous run (edge over the whole period)")
    out.append("")
    out.append("Daily guards on, no drawdown halt / profit target, fixed risk per trade.")
    out.append("")
    out.append("| Dataset | Period | Trades | Win % | PF | Net $ | Avg trade $ | Avg R | Max DD $ | Worst day $ | Sharpe | Long $ | Short $ |")
    out.append("|---|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|")
    for r in rows:
        if r["trades"] == 0:
            out.append(f"| {r['label']} | {r['period']} | 0 | | | | | | | | | | |")
            continue
        out.append(f"| {r['label']} | {r['period']} | {r['trades']} | {r['win_rate']:.1f} | "
                   f"{r['profit_factor']:.2f} | {fmt_money(r['net'])} | {r['avg_trade']:.1f} | "
                   f"{r['avg_r']:+.3f} | {fmt_money(r['max_dd'])} | {fmt_money(r['worst_day'])} | "
                   f"{r['sharpe']:.2f} | {fmt_money(r['long_net'])} | {fmt_money(r['short_net'])} |")
    out.append("")
    out.append(f"## Prop evaluations (50K, ${p.profit_target:.0f} target, ${p.max_drawdown:.0f} "
               f"{p.dd_mode.lower()} trailing max loss)")
    out.append("")
    out.append(f"Rolling evaluations: a fresh 50K account is started every {EVAL_EVERY} trading days "
               f"(overlapping, so attempts are not independent). Each ends PASSED at the target, "
               f"FAILED when the trailing max-loss floor is touched intrabar, or TIMEOUT after "
               f"{EVAL_MAX_DAYS} trading days. 'Consistent' = % of passes whose best day was <= 50% "
               "of the target (Topstep-style consistency rule).")
    out.append("")
    out.append("| Dataset | Attempts | Pass % | Fail % | Timeout % | Consistent passes % | Median days to pass | Median days to fail | Avg P&L of timeouts $ |")
    out.append("|---|---:|---:|---:|---:|---:|---:|---:|---:|")
    for e in evals:
        out.append(f"| {e['label']} | {e['attempts']} | {e['pass']:.1f} | {e['fail']:.1f} | "
                   f"{e['timeout']:.1f} | {e['consistent']:.1f} | {e['days_pass']:.0f} | "
                   f"{e['days_fail']:.0f} | {e['timeout_pnl']:+,.0f} |")
    if yearly:
        out.append("")
        out.append("## Net $ by year (10-year runs, continuous)")
        out.append("")
        years = sorted(set().union(*[set(y.index) for y in yearly.values()]))
        out.append("| Year | " + " | ".join(yearly) + " |")
        out.append("|---|" + "---:|" * len(yearly))
        for yr in years:
            cells = []
            for y in yearly.values():
                cells.append(f"{fmt_money(y.loc[yr, 'sum'])} ({int(y.loc[yr, 'count'])})" if yr in y.index else "-")
            out.append(f"| {yr} | " + " | ".join(cells) + " |")
    out.append("")
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--no-report", action="store_true")
    args = ap.parse_args()
    p = Params()
    rows, evals, yearly = run_all(p)
    text = report(p, rows, evals, yearly)
    print(text)
    if not args.no_report:
        (Path(__file__).resolve().parent / "RESULTS.md").write_text(text)


if __name__ == "__main__":
    main()
